planningTime: 120
touchLinks: [ "LFinger11_link", "LFinger12_link", "LFinger13_link",
"LFinger21_link",  "LFinger22_link",  "LFinger23_link",
"LFinger31_link",  "LFinger32_link",  "LFinger33_link",
"LFinger41_link",  "LFinger42_link",  "LFinger43_link",
"LThumb1_link", "LThumb2_link",
 "l_gripper", "LHandTouchBack_frame"]
eefPosClosed: [0.02]
eefPosOpen: [0.98]
eefCmdScope: "/pepper_dcm/LeftHand_controller/command"
frameArm: "base_footprint"
graspRot: [-1.5708, 0, 0]
goalJointTolerance: 0.01 #rad
goalPositionTolerance: 0.01 #m
goalOrientationTolerance: 0.5 #r
graspThroughDistance: 0.0
approachDesiredDistance: 0.12
approachMinDistance: 0.09
liftUpDesiredDistance: 0.08
liftUpMinDistance: 0.04
retreatDesiredDistance: 0.07
retreatMinDistance: 0.03
anglePitchInc: 0.01 # pi/8
anglePitchMax: 0.01 # pi/4
angleYawInc: 0.01 # pi/8
angleYawMax: 0.01 # pi/4
transInc: 0.001
transMax: 0.0
placeXInc: 0.015
placeYZInc: 0.04
placeXMax: 0.08
placeYMax: 0.10
placeZMax: 0.17
heightSkipTop: 0.005
heightSkipBottom: 0.05
heightInc: 0.01
